apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-balance-deployment
  labels:
    app: api-balance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-balance
  template:
    metadata:
      labels:
        app: api-balance
    spec:
      containers:
      - name: api-balance
        image: api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-balance-service
spec:
  selector:
    app: api-balance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80