#Base image
#----------
FROM mcr.microsoft.com/dotnet/aspnet:7.0.1-jammy AS baserelease

#Force invalidate docker cache
#-----------------------------
ARG CACHE_DATE=1900-01-01

WORKDIR /app

#Copy app
#--------
COPY release/* /app/

ENTRYPOINT ["./Web"]