#Base image with Chrome
#-----------------------
FROM mcr.microsoft.com/dotnet/aspnet:7.0.1-jammy AS baserelease

#BUILD
#------

FROM mcr.microsoft.com/dotnet/sdk:7.0.101-jammy AS builder

#Install Git
RUN apt-get -y update
RUN apt-get -y install git

WORKDIR /app

#Force invalidate docker cache
ARG CACHE_DATE=1900-01-01

# Download tests from Git
RUN git clone https://github.com/danilotessler/MyWebApp.git

#Build test suit
WORKDIR /app/MyWebApp/Web
RUN dotnet restore -r linux-x64 /p:PublishReadyToRun=true
#RUN dotnet publish -c Release -o /app/release/ -r linux-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
RUN dotnet publish -c Release -o /app/release/ -r linux-x64 --self-contained true --no-restore /p:PublishReadyToRun=true

#RUN
#------
FROM baserelease AS release

#Copy the test app
WORKDIR /app

COPY --from=builder /app/release/* /app/

ENTRYPOINT ["./Web"]